branch-defaults:
  default:
    environment: null
    group_suffix: null
  task-9:
    environment: develop
    group_suffix: null
deploy:
  artifact: deploy.zip
global:
  application_name: utrennik-bff-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
