plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: 'npm'

service: authorization-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: utrennik
  stage: dev
  region: eu-west-1

functions:
  basicAuthorizer:
    handler: src/handlers/basicAuthorizer.basicAuthorizer
